security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # Provider factice (vide) car on n'a pas d'utilisateurs pour l'instant
        in_memory:
            memory: ~

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: in_memory
            # Pas d'authentification activée pour le moment

    # Pas de règles d'accès pour l'instant (tout est public)
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }